### ISSUE TITLE
add a live link

### ISSUE THREAD

**Issue by shahriarshafin** [Faisal7822/calculator#1]
### Add a live link to your project. Checkout this demo:

<img width="1336" alt="Screenshot 2023-07-05 at 3 07 43 PM" src="https://github.com/Faisal7822/calculator/assets/32214710/d064e1f6-1852-4876-af6b-7293ed620f66">

**Comment by Faisal7822** [comment]
Thanks @ shariar shahfin

**Comment by Faisal7822** [comment]
Thanks @ shariar shahfin
